M48
; DRILL file {KiCad 7.0.9} date Thursday, November 23, 2023 at 04:15:03 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-23T16:15:03+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.800
%
G90
G05
T1
X186.395Y-87.195
X186.395Y-114.195
T2
X195.395Y-91.695
X195.395Y-109.97
T3
X176.395Y-100.695
T0
M30
