M48
; DRILL file {KiCad (6.0.7-1)-1} date Tuesday, 20 September 2022 at 05:51:28 am
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-20T05:51:28+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X82.04Y-64.31
X82.04Y-113.32
X140.03Y-113.31
X140.04Y-64.33
T0
M30
