M48
; DRILL file {KiCad (6.0.7-1)-1} date Sunday, 21 May 2023 at 11:10:57 am
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-21T11:10:57+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X82.04Y-64.31
X82.04Y-113.32
X140.03Y-113.31
X140.04Y-64.33
T0
M30
