M48
; DRILL file {KiCad 7.0.9} date Saturday, November 25, 2023 at 12:12:53 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-25T12:12:53+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X136.02Y-39.675
X136.02Y-132.385
X166.04Y-64.44
X196.02Y-39.675
X196.02Y-132.385
T0
M30
