M48
; DRILL file {KiCad (6.0.7-1)-1} date Sunday, 29 October 2023 at 12:13:12 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-29T12:13:12+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.800
%
G90
G05
T1
X166.438Y-96.868
X193.438Y-96.868
T2
X159.384Y-106.868
X170.938Y-87.868
X179.938Y-78.485
X200.491Y-106.868
T3
X179.938Y-106.868
T0
M30
