M48
; DRILL file {KiCad (6.0.7-1)-1} date Sunday, 29 October 2023 at 11:35:49 am
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-29T11:35:49+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.572
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C12.700
%
G90
G05
T1
X91.749Y-74.36
X152.074Y-74.36
T2
X71.111Y-87.25
X168.901Y-73.725
T3
X91.749Y-83.885
X91.749Y-83.885
X152.074Y-83.885
X152.074Y-83.885
T0
M30
