M48
; DRILL file {KiCad 7.0.9} date Tuesday, December 05, 2023 at 07:44:04 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-05T19:44:04+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.3551Y-1.562
X5.3551Y-5.212
X6.537Y-2.537
X7.7173Y-1.562
X7.7173Y-5.212
T0
M30
