function layout()
return {
keyCommands = {
{combos = {{key = "F2", reformers = {"LShift", }}, }, down = iCommandMarkerStatePlane, name = "Aircraft Labels", category = "Labels"},
{combos = {{key = "F10", reformers = {"LShift", }}, }, down = iCommandMarkerState, name = "All Labels", category = "Labels"},
{combos = {{key = "B", reformers = {"LAlt", }}, }, down = iCommandViewBriefing, name = "Briefing window", category = "General"},
{combos = {{key = "J", reformers = {"LShift", }}, }, down = iCommandViewCameraJiggle, name = "Camera jiggle toggle", category = "View Extended"},
{combos = {{key = "Num+", reformers = {"RCtrl", }}, }, down = iCommandViewPlus, name = "Camera ordnance tracking", category = "View Extended"},
{combos = {{key = "\\"}, }, down = iCommandToggleCommandMenu, name = "Communication menu", category = "Communications"},
{combos = {{key = "Y", reformers = {"LAlt", }}, }, down = iCommandViewCoordinatesInLinearUnits, name = "Coordinates units change", category = "General"},
{combos = {{key = "Esc"}, }, down = iCommandQuit, name = "End mission", category = "General"},
{combos = {{key = "F1"}, }, down = iCommandViewCockpit, name = "F1 Cockpit view", category = "View"},
{combos = {{key = "F1", reformers = {"LAlt", }}, }, down = iCommandViewHUDOnlyOnOff, name = "F1 HUD only view switch", category = "View"},
{combos = {{key = "F1", reformers = {"LWin", }}, }, down = iCommandViewPitHeadOnOff, name = "F1 Head shift movement on / off", category = "View"},
{combos = {{key = "F1", reformers = {"LCtrl", }}, }, down = iCommandNaturalViewCockpitIn, name = "F1 Natural head movement view", category = "View"},
{combos = {{key = "F10", reformers = {"LCtrl", }}, }, down = iCommandViewAWACSJump, name = "F10 Jump to theater map view over current point", category = "View"},
{combos = {{key = "F10"}, }, down = iCommandViewAWACS, name = "F10 Theater map view", category = "View"},
{combos = {{key = "F11"}, }, down = iCommandViewFree, name = "F11 Airport free camera", category = "View"},
{combos = {{key = "F11", reformers = {"LCtrl", }}, }, down = iCommandViewFreeJump, name = "F11 Jump to free camera", category = "View"},
{combos = {{key = "Num/", reformers = {"LAlt", }}, }, down = iCommandViewSlowDown, name = "F11 camera moving backward", category = "View"},
{combos = {{key = "Num*", reformers = {"LAlt", }}, }, down = iCommandViewSpeedUp, name = "F11 camera moving forward", category = "View"},
{combos = {{key = "F12", reformers = {"LCtrl", }}, }, down = iCommandViewMirage, name = "F12 Civil traffic view", category = "View"},
{combos = {{key = "F12"}, }, down = iCommandViewStatic, name = "F12 Static object view", category = "View"},
{combos = {{key = "F12", reformers = {"LShift", }}, }, down = iCommandViewLocomotivesToggle, name = "F12 Trains/cars toggle", category = "View"},
{combos = {{key = "F2"}, }, down = iCommandViewAir, name = "F2 Aircraft view", category = "View"},
{combos = {{key = "F2", reformers = {"RAlt", }}, }, down = iCommandViewFromTo, name = "F2 Toggle camera position", category = "View"},
{combos = {{key = "F2", reformers = {"LAlt", }}, }, down = iCommandViewLocal, name = "F2 Toggle local camera control", category = "View"},
{combos = {{key = "F2", reformers = {"LCtrl", }}, }, down = iCommandViewMe, name = "F2 View own aircraft", category = "View"},
{combos = {{key = "F3", reformers = {"LCtrl", }}, }, down = iCommandViewTowerJump, name = "F3 Fly-By jump view", category = "View"},
{combos = {{key = "F3"}, }, down = iCommandViewTower, name = "F3 Fly-By view", category = "View"},
{combos = {{key = "F4", reformers = {"LCtrl", }}, }, down = iCommandViewChase, name = "F4 Chase view", category = "View"},
{combos = {{key = "F4"}, }, down = iCommandViewRear, name = "F4 Look back view", category = "View"},
{combos = {{key = "F5", reformers = {"LCtrl", }}, }, down = iCommandViewFightGround, name = "F5 Ground hostile view", category = "View"},
{combos = {{key = "F5"}, }, down = iCommandViewFight, name = "F5 nearest AC view", category = "View"},
{combos = {{key = "F6"}, }, down = iCommandViewWeapons, name = "F6 Released weapon view", category = "View"},
{combos = {{key = "F6", reformers = {"LCtrl", }}, }, down = iCommandViewWeaponAndTarget, name = "F6 Weapon to target view", category = "View"},
{combos = {{key = "F7", reformers = {"LCtrl", }}, }, down = iCommandViewJFO, name = "F7 Ground JFO/JTAC view", category = "View"},
{combos = {{key = "F7"}, }, down = iCommandViewGround, name = "F7 Ground unit view", category = "View"},
{combos = {{key = "F8", reformers = {"RAlt", }}, }, down = iCommandViewTargetType, name = "F8 Player targets/All targets filter", category = "View"},
{combos = {{key = "F8"}, }, down = iCommandViewTargets, name = "F8 Target view", category = "View"},
{combos = {{key = "F9", reformers = {"LAlt", }}, }, down = iCommandViewLndgOfficer, name = "F9 Landing signal officer view", category = "View"},
{combos = {{key = "F9"}, }, down = iCommandViewNavy, name = "F9 Ship view", category = "View"},
{combos = {{key = "]", reformers = {"LShift", }}, }, down = iCommandViewFastKeyboard, name = "Fast keyboard turn speed", category = "View"},
{combos = {{key = "[", reformers = {"LShift", }}, }, down = iCommandViewFastMouse, name = "Fast mouse turn speed", category = "View"},
{combos = {{key = "Pause", reformers = {"RCtrl", }}, }, down = iCommandGraphicsFrameRate, name = "Frame rate counter - Service info", category = "General"},
{combos = {{key = "Tab", reformers = {"RCtrl", "RShift", }}, }, down = iCommandRecoverHuman, name = "Get new plane - respawn", category = "General"},
{combos = {{key = "Y", reformers = {"LCtrl", }}, }, down = iCommandInfoOnOff, name = "Info bar view toggle", category = "General"},
{combos = {{key = "J", reformers = {"RAlt", }}, }, down = iCommandPlaneJump, name = "Jump into other aircraft", category = "General"},
{combos = {{key = "K", reformers = {"LAlt", }}, }, down = iCommandViewKeepTerrain, name = "Keep terrain camera altitude", category = "View Extended"},
{combos = {{key = "Num.", reformers = {"RCtrl", }}, }, down = iCommandViewTerrainLock, name = "Lock terrain view", category = "View Padlock"},
{combos = {{key = "Num."}, }, down = iCommandViewLock, name = "Lock view (cycle padlock)", category = "View Padlock"},
{combos = {{key = "F6", reformers = {"LShift", }}, }, down = iCommandMarkerStateRocket, name = "Missile Labels", category = "Labels"},
{combos = {{key = "Tab"}, }, down = iCommandChat, name = "Multiplayer chat - mode All", category = "General"},
{combos = {{key = "Tab", reformers = {"RCtrl", }}, }, down = iCommandFriendlyChat, name = "Multiplayer chat - mode Allies", category = "General"},
{combos = {{key = "]", reformers = {"LAlt", }}, }, down = iCommandViewNormalKeyboard, name = "Normal keyboard turn speed", category = "View"},
{combos = {{key = "[", reformers = {"LAlt", }}, }, down = iCommandViewNormalMouse, name = "Normal mouse turn speed", category = "View"},
{combos = {{key = "Delete", reformers = {"LAlt", }}, }, down = iCommandViewObjectIgnore, name = "Object exclude ", category = "View Extended"},
{combos = {{key = "Insert", reformers = {"LAlt", }}, }, down = iCommandViewObjectsAll, name = "Objects all excluded - include", category = "View Extended"},
{combos = {{key = "PageDown", reformers = {"LCtrl", }}, }, down = iCommandViewSwitchForward, name = "Objects switching direction forward ", category = "View Extended"},
{combos = {{key = "PageUp", reformers = {"LCtrl", }}, }, down = iCommandViewSwitchReverse, name = "Objects switching direction reverse ", category = "View Extended"},
{combos = {{key = "Pause"}, }, down = iCommandBrakeGo, name = "Pause", category = "General"},
{combos = {{key = "'"}, }, down = iCommandScoresWindowToggle, name = "Score window", category = "General"},
{combos = {{key = "SysRQ"}, }, down = iCommandScreenShot, name = "Screenshot", category = "General"},
{combos = {{key = "'", reformers = {"LAlt", }}, }, down = iCommandMissionResourcesManagement, name = "Show Mission Resources Management window", category = "General"},
{combos = {{key = "'", reformers = {"RShift", }}, }, down = iCommandDebriefing, name = "Show debriefing window", category = "General"},
{combos = {{key = "]", reformers = {"LCtrl", }}, }, down = iCommandViewSlowKeyboard, name = "Slow keyboard turn speed", category = "View"},
{combos = {{key = "[", reformers = {"LCtrl", }}, }, down = iCommandViewSlowMouse, name = "Slow mouse turn speed", category = "View"},
{combos = {{key = "\\", reformers = {"LShift", }}, }, down = ICommandSwitchDialog, name = "Switch dialog", category = "Communications"},
{combos = {{key = "\\", reformers = {"LCtrl", }}, }, down = ICommandSwitchToCommonDialog, name = "Switch to main menu", category = "Communications"},
{combos = {{key = "Z", reformers = {"LCtrl", }}, }, down = iCommandAccelerate, name = "Time accelerate", category = "General"},
{combos = {{key = "Z", reformers = {"LAlt", }}, }, down = iCommandDecelerate, name = "Time decelerate", category = "General"},
{combos = {{key = "Z", reformers = {"LShift", }}, }, down = iCommandNoAcceleration, name = "Time normal", category = "General"},
{combos = {{key = "NumLock"}, }, down = iCommandViewUnlock, name = "Unlock view (stop padlock)", category = "View Padlock"},
{combos = {{key = "F9", reformers = {"LShift", }}, }, down = iCommandMarkerStateShip, name = "Vehicle & Ship Labels", category = "Labels"},
{combos = {{key = "Num5"}, }, pressed = iCommandViewCenter, name = "View Center", category = "View"},
{combos = {{key = "Num1"}, }, pressed = iCommandViewDownLeftSlow, up = iCommandViewStopSlow, name = "View Down Left slow", category = "View"},
{combos = {{key = "Num3"}, }, pressed = iCommandViewDownRightSlow, up = iCommandViewStopSlow, name = "View Down Right slow", category = "View"},
{combos = {{key = "Num2"}, }, pressed = iCommandViewDownSlow, up = iCommandViewStopSlow, name = "View Down slow", category = "View"},
{combos = {{key = "Num4"}, }, pressed = iCommandViewLeftSlow, up = iCommandViewStopSlow, name = "View Left slow", category = "View"},
{combos = {{key = "Num6"}, }, pressed = iCommandViewRightSlow, up = iCommandViewStopSlow, name = "View Right slow", category = "View"},
{combos = {{key = "Num7"}, }, pressed = iCommandViewUpLeftSlow, up = iCommandViewStopSlow, name = "View Up Left slow", category = "View"},
{combos = {{key = "Num9"}, }, pressed = iCommandViewUpRightSlow, up = iCommandViewStopSlow, name = "View Up Right slow", category = "View"},
{combos = {{key = "Num8"}, }, pressed = iCommandViewUpSlow, up = iCommandViewStopSlow, name = "View Up slow", category = "View"},
{combos = {{key = "Delete", reformers = {"RCtrl", }}, }, down = iCommandViewAll, name = "View all mode", category = "View Extended"},
{combos = {{key = "Num2", reformers = {"RShift", }}, }, pressed = iCommandViewDown, up = iCommandViewStop, name = "View down", category = "View"},
{combos = {{key = "Num1", reformers = {"RShift", }}, }, pressed = iCommandViewDownLeft, up = iCommandViewStop, name = "View down left", category = "View"},
{combos = {{key = "Num3", reformers = {"RShift", }}, }, pressed = iCommandViewDownRight, up = iCommandViewStop, name = "View down right", category = "View"},
{combos = {{key = "End", reformers = {"RCtrl", }}, }, down = iCommandViewEnemies, name = "View enemies mode", category = "View Extended"},
{combos = {{key = "Home", reformers = {"RCtrl", }}, }, down = iCommandViewFriends, name = "View friends mode", category = "View Extended"},
{combos = {{key = "Num4", reformers = {"RShift", }}, }, pressed = iCommandViewLeft, up = iCommandViewStop, name = "View left", category = "View"},
{combos = {{key = "Num6", reformers = {"RShift", }}, }, pressed = iCommandViewRight, up = iCommandViewStop, name = "View right", category = "View"},
{combos = {{key = "Num8", reformers = {"RShift", }}, }, pressed = iCommandViewUp, up = iCommandViewStop, name = "View up", category = "View"},
{combos = {{key = "Num7", reformers = {"RShift", }}, }, pressed = iCommandViewUpLeft, up = iCommandViewStop, name = "View up left", category = "View"},
{combos = {{key = "Num9", reformers = {"RShift", }}, }, pressed = iCommandViewUpRight, up = iCommandViewStop, name = "View up right", category = "View"},
{combos = {{key = "Num*", reformers = {"RCtrl", }}, }, pressed = iCommandViewExternalZoomIn, up = iCommandViewExternalZoomInStop, name = "Zoom external in", category = "View"},
{combos = {{key = "NumEnter", reformers = {"RCtrl", }}, }, down = iCommandViewExternalZoomDefault, name = "Zoom external normal", category = "View"},
{combos = {{key = "Num/", reformers = {"RCtrl", }}, }, pressed = iCommandViewExternalZoomOut, up = iCommandViewExternalZoomOutStop, name = "Zoom external out", category = "View"},
{combos = {{key = "Num*", reformers = {"RShift", }}, }, pressed = iCommandViewForward, up = iCommandViewForwardStop, name = "Zoom in", category = "View"},
{combos = {{key = "Num*"}, }, pressed = iCommandViewForwardSlow, up = iCommandViewForwardSlowStop, name = "Zoom in slow", category = "View"},
{combos = {{key = "NumEnter"}, }, down = iCommandViewAngleDefault, name = "Zoom normal", category = "View"},
{combos = {{key = "Num/", reformers = {"RShift", }}, }, pressed = iCommandViewBack, up = iCommandViewBackStop, name = "Zoom out", category = "View"},
{combos = {{key = "Num/"}, }, pressed = iCommandViewBackSlow, up = iCommandViewBackSlowStop, name = "Zoom out slow", category = "View"},
},
axisCommands = {
},
}
end