M48
; DRILL file {KiCad (6.0.7-1)-1} date Monday, 30 October 2023 at 08:06:20 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-30T20:06:20+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X31.81Y-91.81
X34.81Y-50.81
X71.81Y-54.81
T0
M30
