M48
; DRILL file {KiCad 7.0.9} date Sunday, December 03, 2023 at 08:32:57 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-03T08:32:57+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.600
%
G90
G05
T1
X77.551Y-77.677
X104.449Y-75.323
T2
X81.801Y-68.772
X91.937Y-87.209
X98.718Y-67.302
T3
X90.477Y-70.523
T0
M30
